apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: 'ayanlab'
  namespace: 'default'
  labels:
    dashboards: 'ayanlab'
spec:
  external:
    url: https://ayanlab.grafana.net/
    apiKey:
      name: grafana-cloud-credentials
      key: GRAFANA_CLOUD_INSTANCE_TOKEN